### PR TITLE
tvheadend: fixes cm-online

### PR DESCRIPTION
**Pull request by CvH**
This fixes the cm-online bug OpenELEC/OpenELEC.tv/issues/4745

- Tvh respect now the global OE setting "wait for network". This could lead to problems, lets see :)
- removed the broken "wait for network" setting at the addon
- added a Tvh delayed start option to let people easily workaround their dvb hardware problems without messing with autostart.sh or the tvh startscript
- updated Tvh to 4.0.8~15 (rebuild has to be done anyway) + awesome patch file :(

### CODE REVIEW

**Comment by CvH** [comment]
**!! NO 6.0 BACKPORT !!**

**Comment by lrusak** [comment]
squash into one commit please

**Comment by CvH** [comment]
done

**Comment by CvH** [comment]
@lrusak I added a commit to change the addon_name pls have a look if it fu up the repo or something ?! I squash it if you gave okay.

**Comment by lrusak** [comment]
Yes that's fine, `PKG_ADDON_NAME` is purely cosmetic, you can squash.

**Pull request merged**
