### PR TITLE
oscam: preserve config files timestamps

### PR DESCRIPTION
**Pull request by glenvt18**
Dont't modify timestamps of the existing files on each start.

### CODE REVIEW

**Comment by chewitt** [comment]
can you give a longer explanation of the problem this solves pls.

**Comment by glenvt18** [comment]
If some of the listed files are not empty their timestamps are also updated on each start of the daemon. That is confusing and may cause problems if you want to keep some of those files in sync or generate them every time a "master" source changes.
It also generates unnecessary writes to a flash filesystem.
BTW. Creation of the empty files is cosmetic and not needed at all. Only oscam.conf is required to start the daemon first time.

**Comment by lrusak** [comment]
can you bump the PKG_REV and update the changelog.txt?

similar to this commit, https://github.com/OpenELEC/unofficial-addons/commit/bc61142e72f4260d2b223e5774cbe5cfc7f4b72f

**Comment by glenvt18** [comment]
Yes. Updated. Also added a "graceful" permission setting for executables. Though they are set twice by kodi (in systemd-addon-wrapper and  kodi-config - "just in case"), that may change in the future.

**Comment by chewitt** [comment]
@lrusak - any objections?

**Comment by lrusak** [comment]
@glenvt18 Please squash all commits into one commit that lists all changes

**Comment by glenvt18** [comment]
Updated.

**Pull request merged**
