### PR TITLE
new addon: sqlite 3.9.0

### PR DESCRIPTION
**Pull request by jamesmacwhite**
Static binary of `sqlite3`, its already part of the OpenELEC source tree but as dependency of Kodi for the libs. I took the package.mk from the source and modified it to build as a console addon, uses the latest version of the SQLite autoconf source package.

### CODE REVIEW

**Comment by lrusak** [comment]
If it's already built then you can simply name the package as something else and use
PKG_DEPENDS_TARGET to make sure the package is built, then pull the needed files from the packages,
see here for an example. https://github.com/lrusak/OpenELEC.tv/blob/b6f0515c144ce275a58090333aee794dab0eabf8/packages/addons/tools/systemd-tools/package.mk

**Comment by jamesmacwhite** [comment]
Hi lrusak,

Thanks for the advice. OK great. So essentially add `PKG_DEPENDS_TARGET="sqlite"`

And the additional functions for building as addon, but I assume I don't need to copy the patches and various `CFLAGS` if already set in the original sqlite package.mk?

**Comment by stefansaraev** [comment]
sqlite3 binary is ~ 500k (less than 100k in compressed squashfs). it should be installed by default

https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/databases/sqlite/package.mk#L79

**Comment by jamesmacwhite** [comment]
Hi,

I couldn't find a binary on my OpenELEC install, I only get the following returned when using `find / -name sqlite`:

`/usr/lib/python2.7/sqlite3`

Which doesn't have it, unless I'm missing something obvious?

**Comment by lrusak** [comment]
@jamesmacwhite I think he means it should be made to be installed by default ;)

**Comment by stefansaraev** [comment]
that's why I say it should be installed by default, and that must tbe done upstream (in openelec main repo) for @lrusak @sraue

**Comment by jamesmacwhite** [comment]
Sorry guys my bad, I thought the previous comment meant it was installed as a binary already somehow.

I mean yeah, that would be great, or if its decided its not going to be done in upstream, I'll amend the PR for unofficial repo.

**Comment by sraue** [comment]
added in the core os with https://github.com/OpenELEC/OpenELEC.tv/commit/3f2105472804270e5621d5fccd15e0e2a11e8f06 , thanks much

**Pull request closed without merging**
