### PR TITLE
Syncthing

### PR DESCRIPTION
**Pull request by awiouy**
This is an attempt to add a community add-on for Syncthing.
I have successfully tested this on my Raspberry Pi 1 and 2.
Thank you for your attention, and regards,
@

### CODE REVIEW

**Comment by chewitt** [comment]
two things:
a) Update the commit message text to be "add Syncthing add-on" or similar
b) Update changelog.txt to show 7.0.0 as the initial release, or flag 4.3.1 as a private/testing release

**Comment by awiouy** [comment]
Ok.

**Comment by chewitt** [comment]
no need to close .. just rebase the last commit and change the message, then force push

**Comment by awiouy** [comment]
Oh! I hardly have experience therewith. Could you please tell me what
I should do now, wrt PR 105 and/or 106.

Thank you in advance for any help you can provide

@

**Pull request closed without merging**
