### PR TITLE
add espeak

### PR DESCRIPTION
**Pull request by mrdominuzq**
i think espeak belongs here :)

### CODE REVIEW

**Comment by stefansaraev** [comment]
we have ESPEAK_SUPPORT in core. I think it was added for someone who makes an addon for blind people. if it works in core, lets not move to unofficial and make blind peoples life a bit  easier, @sraue ?

**Comment by sraue** [comment]
we should keep this in our core OS, because its done for blind users, and its OpenELEC is more easy to use for them if its there

**Comment by sraue** [comment]
another option is to move to the addons if the TTS addon could depend on this addon so its installed automatically

**Comment by stefansaraev** [comment]
> another option is to move to the addons if the TTS addon could depend on this addon so its installed automatically

I dont know that TTS addon, but if it's not openelec specific, depending on our addons is no.

closing this

**Comment by mrdominuzq** [comment]
the only addon i could find depending on espeak is https://github.com/ruuk/service.xbmc.tts

**Pull request closed without merging**
