### PR TITLE
syncthing: update to 0.12.19

### PR DESCRIPTION
**Pull request by awiouy**
Hello,

I have updated syncthing to the latest version, and taken the opportunity to simplify its administration.
I hope the changes agree with you.
Thank you for your attention and regards,
@

### CODE REVIEW

**Comment by lrusak** [comment]
Looks good to me :+1:

**Comment by awiouy** [comment]
Hello,

I fixed a typo in the changelog.
Please commit.
Thank you and regards,
@

**Comment by djgrazzy** [comment]
Development appears to have halted with this version, anyone aware why?

**Comment by awiouy** [comment]
Development has shifted to LibreELEC: https://github.com/LibreELEC/LibreELEC.tv/tree/master/packages/addons/service/syncthing

**Pull request merged**
