### PR TITLE
Enable IPv6 support to tvheadend

### PR DESCRIPTION
**Pull request by ptitgnu**
Hi,

Just added the '-6' option needed to enable IPv6 support.

Thanks :)

### CODE REVIEW

**Comment by stefansaraev** [comment]
some people run tvheadend in v4 only env, where v6 is not available. so no.

**Comment by ptitgnu** [comment]
I don't understand.. This argument will only ask to tvheadend to listen both in v4 and v6.
It doesn't prevent it to work in v4 only environment, just allow people in v6 to access to tvheadend.

**Comment by stefansaraev** [comment]
what happens if you ask tvheadend to listen on v6, but ipv6 kernel module is NOT loaded.

**Comment by stefansaraev** [comment]
dont answer, I'll tell you what will happen. tvheadend fails to listen at all. so dualstack in tvheadend is broken. it must be fixed before this going in, or you make this feature optional, disabled by default, and make it clear (in the config GUI where people enable it) that it MAY break in v4 only environment

**Comment by ptitgnu** [comment]
Mmmh, I had not considered this possibility because the support for IPv6 is compiled inside the OpenELEC linux kernel (built-in, not in module) and therefore, it's not possible to blacklist the module (or maybe by appending a specific argument to the kernel line in the boot loader but why the hell would anyone want to do this ?)

But after all, it's your choice, I can write a little script to add the argument to the file in case of an update of the addon ('cause I'm in IPv6 only here) and the problem will be fixed (for me).

Thanks anyway.

**Comment by stefansaraev** [comment]
still, if you want to make it optional, it's perfectly acceptable then. hints:

https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/addons/service/multimedia/vdr-addon/source/bin/vdr.start#L112-L114
https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/addons/service/multimedia/vdr-addon/source/settings-default.xml#L18
https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/addons/service/multimedia/vdr-addon/source/resources/settings.xml#L34

here how a random optional plugin is done for vdr ^

**Comment by lrusak** [comment]
Is this still relevant?

**Comment by chewitt** [comment]
I'm closing this due to lack of update. Thanks.

**Pull request closed without merging**
