### PR TITLE
Tvheadend Build 2670

### PR DESCRIPTION
**Pull request by wezley98**

### CODE REVIEW

**Comment by stefansaraev** [comment]
pls squash down to one commit.

**Comment by wezley98** [comment]
done.

**Comment by wezley98** [comment]
Hold on this for a while, its not pulling the sources down correctly, al check it out now.

**Comment by wezley98** [comment]
I am confused, how I'm supposed to test the addon build if its pulling from openelec.tv sources but the files don't exist yet, guess somebody uploads them as required?

**Comment by stefansaraev** [comment]
you are supposed to use support/tarbal from tvheadend git sources.

**Comment by wezley98** [comment]
got it :) building now for RPi2 Arm, will update when complete, building for Tvheadend 2675 so I will update pull request if successful build.

**Comment by wezley98** [comment]
ok, build completed fine, just going to push zip to my Pi and install, make sure its working correctly. Don't want to screw to tv up for everybody.

**Comment by wezley98** [comment]
Ok, just tested 2675 on on Pi and web interface and TV works fine. Going to close this PR and open a new one for 2675. Thanks for your help @stefansaraev

**Pull request closed without merging**
