### PR TITLE
The download URL for rsync has changed

### PR DESCRIPTION
**Pull request by chutzimir**

### CODE REVIEW

**Comment by stefansaraev** [comment]
thanks

**Comment by fabien4444** [comment]
Hello Stefan
thanks for your work, especially with your MPD server addon.
I would like to report you that it does not work properly with OpenElec 6.0.
I have install well, process mpd is running but there is no scan!
My music package library is local (in /var/media/), mpd database is always at 1kb size and log file is empty (verbose mode).

Thanks for your support
Fabien

**Comment by fritsch** [comment]
Can you stop mpd and run it manually with the appropriate config switches
and see what happens?

2015-11-03 11:47 GMT+01:00 fabien4444 <notifications@github.com>:

> Hello Stefan
> thanks for your work, especially with your MPD server addon.
> I would like to report you that it does not work properly with OpenElec
> 6.0.
> I have install well, process mpd is running but there is no scan!
> My music package library is local (in /var/media/), mpd database is always
> at 1kb size and log file is empty (verbose mode).
>
> Thanks for your support
> Fabien
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/unofficial-addons/pull/75#issuecomment-153312624>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by fabien4444** [comment]
Hello,
i changed config file with music_directory = "/var/media/my music" in addons folder and delete config file in userdata.
I start again mpd (mpd.start), file config is well deployed in userdata/addons, but no scan :(

**Comment by fritsch** [comment]
Please also post your mpd.conf and try to start mpd directly from the shell:
/path/to/mpd --kill
/path/to/mpd /path/to/your/config --no-daemon

**Comment by fabien4444** [comment]
Thanks for the advice
i will do it this evening at home and report to you

**Comment by stefansaraev** [comment]
@fabien4444 this is dev area, not help center. and you are commenting under absolutely unrelated pull request. I am quite sure @chutzimir would not like all the junk mail he received today.

**Comment by fabien4444** [comment]
Sorry Stefan, i did not know where to post to report the issue to you. I am not the only one to report it in OE forum support.
I will not post again.

**Pull request merged**
