### PR TITLE
Build fixes

### PR DESCRIPTION
**Pull request by lrusak**
@stefansaraev can you check this over? These are changes I needed to make to build the entire unofficial repo.

### CODE REVIEW

**Comment by stefansaraev** [comment]
:+1: if it all builds

**Comment by stefansaraev** [comment]
also, I would suggest you bump everything for 7.0. drop whatever has no chance to compile or whatever you dont want to maintain (chromium is one candidate) then cut off old repos here https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/addons/repository/repository.unofficial.addon.pro/sources/addon.xml#L8-L17 <= keep only one directory: addons/7.0.

**Comment by lrusak** [comment]
Yea I plan on it. I just need to get these changes in and then get it branched for 6.0 and 6.0

Thanks for the tips :)

**Comment by lrusak** [comment]
Good to go :+1:

**Pull request merged**
