### PR TITLE
remove addon: makekmv

### PR DESCRIPTION
**Pull request by stefansaraev**
because enough,

### CODE REVIEW

**Comment by lrusak** [comment]
Any reason for this?

**Comment by fritsch** [comment]
Besides that it is illegal, nothing.
Am 21.08.2015 8:26 nachm. schrieb "Lukas Rusak" <notifications@github.com>:

**Comment by lrusak** [comment]
That's a good enough reason for me :+1:

**Comment by stefansaraev** [comment]
fyi, it's already removed from repos. so better push the damn button. push #78 too

**Comment by the-dreamer** [comment]
Maybe makemkv is illegal in some countries. Maybe therefore to distribute such binaries is illegal. But i don't think that a projekt file which could build a binary is illegal. 
I assume that many people want to playback discs or whatever on OE. So if someone want makemkv he is on his own and has to build it by him self. Please keep it the project on git and disable it only for  build to unofficial-repo.

**Comment by stefansaraev** [comment]
^^ ha. it seems we have new repo maintainer. thanks for taking over. @the-dreamer 

ping @sraue could you please discuss the details with him ?

**Comment by the-dreamer** [comment]
do talk about makemkv or complete unofficial repo?

**Pull request closed without merging**
