### PR TITLE
nss 3.22.2 with nspr 4.12

### PR DESCRIPTION
**Pull request by awiouy**
Hello,

I just wanted to check whether nss with nspr would build for RPi2: they do!
I could however not run the test suite (see nss_02 patch), whose build fails miserably.
Neither could I test nss and nspr against Chromium.
Do therefore not commit this PR, which is for discussion only.

So here is a question to start the discussion: what is missing to run Chromium on OpenELEC for RPi?

Thank you for your attention, and regards,
@

### CODE REVIEW

**Comment by lrusak** [comment]
>So here is a question to start the discussion: what is missing to run Chromium on OpenELEC for RPi?

mainly xorg

**Comment by awiouy** [comment]
Ah!
This is not apparent from the PKG_DEPEND_TARGET variable of the chromium package.mk file, according to which only pciutils was not suitable for RPi.
Which parts of X.org would be missing?
@

**Comment by lrusak** [comment]
Everything, we don't include xorg for arm devices on OpenELEC.

**Comment by awiouy** [comment]
Bummer!
This closes the discussion :)
I hope this PR may nevertheless be useful. Someone should test it, though.
Cheers
@

**Comment by awiouy** [comment]
Just out of curiosity, I tried to build chromium for RPi2, after settings the PKG_DEPEND_TARGET variable of the requisite packages to "any". Everything builds, but for chromium, due to this:

Traceback (most recent call last):
  File "/home/jc/Projects/OpenELEC.tv-6.0.1/build.OpenELEC-RPi2.arm-6.0.1/toolchain/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/jc/Projects/OpenELEC.tv-6.0.1/build.OpenELEC-RPi2.arm-6.0.1/toolchain/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha512
gyp: Call to 'python ../tools/clang/scripts/update.py --print-revision' returned exit status 0 while in /home/jc/Projects/OpenELEC.tv-6.0.1/build.OpenELEC-RPi2.arm-6.0.1/chromium-48.0.2564.82/build/all.gyp.

The build does not seem to find libssl. Any clue why ?
@

**Pull request merged**
